// Import all core blocks
// TODO: maybe add filter to customize this list
import '@blocks/e-accordion/e-accordion.block';
import '@blocks/e-accordion-group/e-accordion-group.block';
import '@blocks/e-breadcrumbs/e-breadcrumbs.block';
import '@blocks/e-button/e-button.block';
import '@blocks/e-gallery/e-gallery.block';
import '@blocks/e-image/e-image.block';
import '@blocks/e-picker-query-loop/e-picker-query-loop.block';
import '@blocks/e-post-template/e-post-template.block';
import '@blocks/e-query-loop/e-query-loop.block';
import '@blocks/e-slider/e-slider.block';
import '@blocks/e-svg/e-svg.block';
import '@blocks/e-tab-container/e-tab-container.block';
import '@blocks/e-table/e-table.block';
import '@blocks/e-table-cell/e-table-cell.block';
import '@blocks/e-table-row/e-table-row.block';
import '@blocks/e-tabs/e-tabs.block';
import '@blocks/l-404/l-404.block';
import '@blocks/l-flexible-container/l-flexible-container.block';
import '@blocks/l-footer/l-footer.block';
import '@blocks/l-formatted-content/l-formatted-content.block';
import '@blocks/l-header/l-header.block';
import '@blocks/l-mobile-nav/l-mobile-nav.block';
import '@blocks/l-nav-menu/l-nav-menu.block';
import '@blocks/l-post-card/l-post-card.block';
import '@blocks/l-section/l-section.block';
import '@blocks/l-site-logo/l-site-logo.block';
import '@blocks/e-icon-picker/e-icon-picker.block';
