/**
 * AppliedClassesViewer — Toolbar button (eye icon) that reveals a popover
 * listing all Tailwind classes generated by responsive settings for the
 * current block. Rendered inside BlockControls > ToolbarGroup in the
 * block toolbar so it covers all panels (spacing, layout, borders).
 *
 * Classes are grouped by panel group (Spacing, Display & Layout, Border)
 * for easier scanning.
 */
import { getBlockType } from '@wordpress/blocks';
import { Popover, ToolbarButton } from '@wordpress/components';
import { useMemo, useState } from '@wordpress/element';
import { __ } from '@wordpress/i18n';
import { postList } from '@wordpress/icons';

import { useBlockParent } from '@webentorCore/blocks-utils/_use-block-parent';

import { registry } from '../registry';
import { BlockPanelProps, ClassGenContext, PanelGroup } from '../types';

interface ClassGroup {
  group: PanelGroup;
  label: string;
  classes: string[];
}

const GROUP_LABELS: Record<PanelGroup, string> = {
  spacing: 'Spacing',
  displayLayout: 'Display & Layout',
  border: 'Border',
  blockLink: 'Block Link',
};

/** Panel group render order */
const GROUP_ORDER: PanelGroup[] = [
  'spacing',
  'displayLayout',
  'border',
  'blockLink',
];

/**
 * Collect responsive-settings classes grouped by panel group.
 * Same logic as generateClassNames in utils.ts but without useBlockProps.
 */
const collectGroupedClasses = (
  attributes: Record<string, any>,
  blockName: string,
  parentAttributes: Record<string, any> | undefined,
  orderedBreakpoints: string[],
): ClassGroup[] => {
  const blockSettings = getBlockType(blockName);
  const supports = blockSettings?.supports;

  const context: ClassGenContext = {
    blockName,
    supports,
    parentBlockAttributes: parentAttributes,
    breakpoints: orderedBreakpoints,
  };

  const allSettings = registry.getAll();

  // Collect all breakpoints present in any attribute
  const breakpoints = new Set<string>();
  for (const def of allSettings) {
    if (!registry.isSupported(supports, def)) continue;
    for (const attrKey of Object.keys(def.attributeSchema)) {
      const attrGroup = attributes[attrKey];
      if (!attrGroup || typeof attrGroup !== 'object') continue;
      for (const prop of Object.values(attrGroup)) {
        const propData = prop as any;
        if (propData?.value) {
          for (const bp of Object.keys(propData.value)) {
            breakpoints.add(bp);
          }
        }
      }
    }
  }

  // Group classes by panelGroup
  const groupMap = new Map<PanelGroup, string[]>();
  for (const bp of breakpoints) {
    for (const def of allSettings) {
      if (!registry.isSupported(supports, def)) continue;
      const generated = def
        .generateClasses(attributes, bp, context)
        .filter(Boolean);
      if (generated.length === 0) continue;

      const existing = groupMap.get(def.panelGroup) ?? [];
      existing.push(...generated);
      groupMap.set(def.panelGroup, existing);
    }
  }

  return GROUP_ORDER.filter((g) => groupMap.has(g)).map((g) => ({
    group: g,
    label: GROUP_LABELS[g],
    classes: groupMap.get(g)!,
  }));
};

export const AppliedClassesViewer = ({
  attributes,
  name,
  breakpoints,
}: BlockPanelProps) => {
  const [isOpen, setIsOpen] = useState(false);
  const parentBlock = useBlockParent();

  const groups = useMemo(
    () =>
      collectGroupedClasses(
        attributes,
        name,
        parentBlock?.attributes,
        breakpoints,
      ),
    [attributes, name, parentBlock?.attributes, breakpoints],
  );

  if (groups.every((g) => g.classes.length === 0)) return null;

  return (
    <>
      <ToolbarButton
        icon={postList}
        label={__('View applied classes', 'webentor')}
        onClick={() => setIsOpen((prev) => !prev)}
        isPressed={isOpen}
      />
      {isOpen && (
        <Popover
          placement="bottom-start"
          onClose={() => setIsOpen(false)}
          shift
        >
          <div
            style={{
              padding: '12px',
              maxWidth: '320px',
              maxHeight: '280px',
              overflow: 'auto',
            }}
          >
            {groups.map((group, gi) => (
              <div key={group.group} style={{ marginTop: gi > 0 ? '12px' : 0 }}>
                <p
                  style={{
                    fontSize: '11px',
                    textTransform: 'uppercase',
                    marginTop: 0,
                    marginBottom: '6px',
                    color: '#757575',
                  }}
                >
                  {group.label}
                </p>
                <div
                  style={{
                    display: 'flex',
                    flexWrap: 'wrap',
                    gap: '4px',
                  }}
                >
                  {group.classes.map((cls, i) => (
                    <code
                      key={`${cls}-${i}`}
                      style={{
                        fontSize: '11px',
                        padding: '2px 6px',
                        background: '#f0f0f0',
                        borderRadius: '3px',
                        whiteSpace: 'nowrap',
                      }}
                    >
                      {cls}
                    </code>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </Popover>
      )}
    </>
  );
};
